# Generated by Django 3.1.4 on 2020-12-06 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sessiontoken',
            new_name='session_token',
        ),
    ]
